version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: 'nanoid'
        versions: '>=4.0.0'
      - dependency-name: '@types/node'
        versions: '>=18.0.0'
      - dependency-name: 'eslint'
        versions: '>=9.0.0'
